site_name: Sample 3
repo_url: https://github.com/A-Baji/mk-docs-sample3
repo_name: Sample 3 Repo
theme:
  name: material

extra:
  version:
    provider: mike

edit_uri: /blob/master/
nav:
  - Home: index.md
